In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [2]:
np.random.seed(101)

In [5]:
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [6]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [8]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [9]:
type(df['W'])

pandas.core.series.Series

In [10]:
df[['W','Z']]

          W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [13]:
df['new']=df['W']+df['Y']

In [14]:
df['new']

A   -1.403420
B    0.032064
C    1.446493
D   -1.440510
E    0.121354
Name: new, dtype: float64

In [15]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [16]:
df.drop('new',axis=1)

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [17]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [18]:
df.drop('new',axis=1,inplace=True)

In [19]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [20]:
df.drop('E')

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [21]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [22]:
df.shape

(5, 4)

In [24]:
df[['Z','X']]

          Z         X
A -1.159119  1.693723
B  0.184502  0.390528
C  0.329646  0.072960
D  0.484752 -0.754070
E  1.996652  1.901755

In [25]:
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [27]:
df.iloc[2] # index --- c

W    0.807706
X    0.072960
Y    0.638787
Z    0.329646
Name: C, dtype: float64

In [28]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [30]:
df.loc['B','Y']

np.float64(0.16690463609281317)

In [31]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  0.302665 -1.706086
B -0.134841  0.166905

In [34]:
booldf=df > 0

In [36]:
df[booldf]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [37]:
df[df>0]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [38]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [39]:
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [45]:
resultdf=df[df['Z']<0]

In [46]:
df[df['Z']<0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119

In [43]:
resultdf['X']

A    1.693723
Name: X, dtype: float64

In [44]:
df[df['Z']<0]['X']

A    1.693723
Name: X, dtype: float64

In [52]:
df[(df['W']>0) | (df['Y']>0)]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
E -0.116773  1.901755  0.238127  1.996652

In [53]:
df[(df['W']>0) & (df['Y']>0)]

          W        X         Y         Z
C  0.807706  0.07296  0.638787  0.329646

In [54]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [55]:
df.reset_index()

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [57]:
newind='CA NY WY OR CO'.split()

In [58]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [59]:
df['States']=newind

In [60]:
df

          W         X         Y         Z States
A  0.302665  1.693723 -1.706086 -1.159119     CA
B -0.134841  0.390528  0.166905  0.184502     NY
C  0.807706  0.072960  0.638787  0.329646     WY
D -0.497104 -0.754070 -0.943406  0.484752     OR
E -0.116773  1.901755  0.238127  1.996652     CO

In [61]:
df.set_index('States')

               W         X         Y         Z
States
CA      0.302665  1.693723 -1.706086 -1.159119
NY     -0.134841  0.390528  0.166905  0.184502
WY      0.807706  0.072960  0.638787  0.329646
OR     -0.497104 -0.754070 -0.943406  0.484752
CO     -0.116773  1.901755  0.238127  1.996652

In [62]:
# index levels
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [63]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [64]:
inside

[1, 2, 3, 1, 2, 3]

In [65]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [66]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [67]:
pd.MultiIndex.from_tuples(hier_index)

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [69]:
df=pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [70]:
df

             A         B
G1 1  0.147027 -0.479448
   2  0.558769  1.024810
   3 -0.925874  1.862864
G2 1 -1.133817  0.610478
   2  0.386030  2.084019
   3 -0.376519  0.230336

In [71]:
df.loc['G1']

          A         B
1  0.147027 -0.479448
2  0.558769  1.024810
3 -0.925874  1.862864

In [72]:
df.index.names

FrozenList([None, None])

In [73]:
df.index.names=['Groups','Num']

In [74]:
df

                   A         B
Groups Num
G1     1    0.147027 -0.479448
       2    0.558769  1.024810
       3   -0.925874  1.862864
G2     1   -1.133817  0.610478
       2    0.386030  2.084019
       3   -0.376519  0.230336

In [77]:
df.loc['G2'].loc[2]['B']

np.float64(2.084018530338962)

In [78]:
df

                   A         B
Groups Num
G1     1    0.147027 -0.479448
       2    0.558769  1.024810
       3   -0.925874  1.862864
G2     1   -1.133817  0.610478
       2    0.386030  2.084019
       3   -0.376519  0.230336

In [79]:
df.xs('G1')

            A         B
Num
1    0.147027 -0.479448
2    0.558769  1.024810
3   -0.925874  1.862864

In [80]:
df.xs(1,level='Num') #xs-cross section , level--name of the column

               A         B
Groups
G1      0.147027 -0.479448
G2     -1.133817  0.610478