In [1]:
import pandas as pd
import numpy as np

In [18]:
df1=pd.DataFrame({'Α': ['Α0', 'Α1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3'], 'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}, index=[0, 1, 2, 3])

df2=pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'], 'B': ['B4', 'B5', 'B6', 'B7'], 'C': ['C4', 'C5', 'C6', 'C7'], 'D': ['D4', 'D5', 'D6', 'D7']}, index=[4, 5, 6, 7])

df3=pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'], 'B': ['B8', 'B9', 'B10', 'B11'], 'C': ['C8', 'C9', 'C10', 'C11'], 'D': ['D8', 'D9', 'D10', 'D11']}, index=[8, 9, 10, 11])

In [24]:
df1

    Α   B   C   D
0  Α0  B0  C0  D0
1  Α1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [25]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [26]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [30]:
pd.concat([df1,df2,df3])

      Α    B    C    D    A
0    Α0   B0   C0   D0  NaN
1    Α1   B1   C1   D1  NaN
2    A2   B2   C2   D2  NaN
3    A3   B3   C3   D3  NaN
4   NaN   B4   C4   D4   A4
5   NaN   B5   C5   D5   A5
6   NaN   B6   C6   D6   A6
7   NaN   B7   C7   D7   A7
8   NaN   B8   C8   D8   A8
9   NaN   B9   C9   D9   A9
10  NaN  B10  C10  D10  A10
11  NaN  B11  C11  D11  A11

In [28]:
pd.concat([df1,df2,df3],axis=1)

      Α    B    C    D    A    B    C    D    A    B    C    D
0    Α0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    Α1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [31]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'Α': ['Α0', 'Α1', 'A2', 'A3'],
                     'Β': ['Β0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['Κ0', 'Κ1', 'K2', 'K3'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [32]:
left

  key   Α   Β
0  K0  Α0  Β0
1  K1  Α1  B1
2  K2  A2  B2
3  K3  A3  B3

In [33]:
right

  key   C   D
0  Κ0  C0  D0
1  Κ1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [36]:
pd.merge(left,right,how='outer',on='key')

  key    Α    Β    C    D
0  K0   Α0   Β0  NaN  NaN
1  K1   Α1   B1  NaN  NaN
2  K2   A2   B2   C2   D2
3  K3   A3   B3   C3   D3
4  Κ0  NaN  NaN   C0   D0
5  Κ1  NaN  NaN   C1   D1

In [39]:
left = pd.DataFrame({
                    'Α': ['Α0', 'Α1', 'A2', 'A3'],
                     'Β': ['Β0', 'B1', 'B2', 'B3']},
                        index= ['K0', 'K1', 'K2', 'K3'])

right = pd.DataFrame({
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']},
index = ['Κ0', 'Κ1', 'K2', 'K3'])

In [40]:
left.join(right)

     Α   Β    C    D
K0  Α0  Β0  NaN  NaN
K1  Α1  B1  NaN  NaN
K2  A2  B2   C2   D2
K3  A3  B3   C3   D3

In [41]:
left.join(right,how='outer')

      Α    Β    C    D
K0   Α0   Β0  NaN  NaN
K1   Α1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3   A3   B3   C3   D3
Κ0  NaN  NaN   C0   D0
Κ1  NaN  NaN   C1   D1