In [4]:
import pandas as pd

In [7]:
pd.read_csv('example.csv')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [8]:
df=pd.read_csv('example.csv')

In [9]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [14]:
df.to_csv('My_output',index=False)

In [15]:
pd.read_csv('My_output')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [37]:
df=pd.read_excel('Excel_sample.xlsx',sheet_name='Sheet1')

In [38]:
df.to_excel('Excel_sample2.xlsx',sheet_name='NewSheet')

In [39]:
pd.read_excel('Excel_sample2.xlsx',sheet_name='NewSheet')

   Unnamed: 0   a   b   c   d
0           0   1   2   3   4
1           1   5   6   7   8
2           2   9  10  11  12
3           3  13  14  15  16
4           4  17  18  19  20

In [26]:
data = pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html')

In [28]:
type(data)

list

In [30]:
data[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547

In [31]:
from sqlalchemy import create_engine

In [32]:
engine=create_engine('sqlite:///:memory:')

In [34]:
df.to_sql('my_table',engine)

5

In [35]:
sqldf=pd.read_sql('my_table',con=engine)

In [36]:
sqldf

   index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15
4      4  16  17  18  19